import Head from 'next/head'
import { StyledHome, StyledText } from '../styles/Home'
import { Clock } from '../components/ClockDigital'
import { ContentsChanger } from '../components/ContentsChanger'
import { MyAppBar } from '../components/AppBar'
import { TimeProvider } from '../components/useTime'

export default function Home() {
  return (
    <StyledHome>
      <Head>
        <title>Clock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TimeProvider>
        <MyAppBar />
        <main >
          <ContentsChanger>
            <StyledText>待っている間はお静かにお願いします</StyledText>
            <Clock />
            <StyledText>15分たったらおかえりください</StyledText>
            <Clock />
          </ContentsChanger>
        </main>
        <MyAppBar />
      </TimeProvider>
    </StyledHome>
  )
}
